from __future__ import annotations

import hmac
import json
import os
import re
import uuid
import zipfile
from datetime import date
from io import BytesIO
from pathlib import Path
from typing import Any, Dict, Optional, List, Tuple

import pandas as pd
import streamlit as st

import launch_runner
import vector_db
from backend import app
from config import settings
from ingestion.db import init_db as init_ingestion_db
from ingestion.errors import (
    DuplicateDocumentError,
    FileTooLargeError,
    InvalidCollectionNameError,
    InvalidFilenameError,
    UnsupportedFileTypeError,
)
from ingestion.models import IngestionStatus
from ingestion.service import build_service
from memory.db import init_db as init_memory_db
from observability import get_observability_handler
from streaming import run_graph_streaming


@st.cache_resource
def _init_ingestion_backend() -> None:
    """One-time setup (per app process) so the upload widget and memory/past-report
    features work without the separate `uvicorn api_main:app` process running --
    mirrors what api_main.py's lifespan hook does on startup."""
    init_ingestion_db()
    init_memory_db()
    try:
        vector_db.ensure_collection()
    except Exception:
        pass


class _StreamlitUploadAdapter:
    """Shim so a Streamlit UploadedFile can be passed to IngestionService.ingest_upload(),
    which only ever touches `.filename` and `.file.read(n)` -- it doesn't require an
    actual fastapi.UploadFile instance, just those two attributes."""

    def __init__(self, uploaded_file) -> None:
        self.filename = uploaded_file.name
        self.file = uploaded_file


# -----------------------------
# Helpers
# -----------------------------
def safe_slug(title: str) -> str:
    s = title.strip().lower()
    s = re.sub(r"[^a-z0-9 _-]+", "", s)
    s = re.sub(r"\s+", "_", s).strip("_")
    return s or "blog"


def bundle_zip(md_text: str, md_filename: str, images_dir: Path) -> bytes:
    buf = BytesIO()
    with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_DEFLATED) as z:
        z.writestr(md_filename, md_text.encode("utf-8"))

        if images_dir.exists() and images_dir.is_dir():
            for p in images_dir.rglob("*"):
                if p.is_file():
                    z.write(p, arcname=str(p))
    return buf.getvalue()


def images_zip(images_dir: Path) -> Optional[bytes]:
    if not images_dir.exists() or not images_dir.is_dir():
        return None
    buf = BytesIO()
    with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_DEFLATED) as z:
        for p in images_dir.rglob("*"):
            if p.is_file():
                z.write(p, arcname=str(p))
    return buf.getvalue()


# -----------------------------
# Markdown renderer that supports local images
# -----------------------------
_MD_IMG_RE = re.compile(r"!\[(?P<alt>[^\]]*)\]\((?P<src>[^)]+)\)")
_CAPTION_LINE_RE = re.compile(r"^\*(?P<cap>.+)\*$")


_ALLOWED_IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".gif", ".webp", ".svg"}

# Same "images" directory convention already used by generate_and_place_images() in
# backend.py and by images_zip()/bundle_zip() below -- not a new location.
_IMAGES_DIR = Path("images")


def _resolve_image_path(src: str) -> Optional[Path]:
    """Resolve a markdown image reference to a local file, strictly confined to the
    images/ directory this app already writes generated images into -- the existing
    trusted directory, not a new one.

    Returns None for anything that would escape it (absolute paths, ../ traversal,
    or a symlink inside images/ whose real target resolves outside it) so the
    caller can skip the reference gracefully instead of ever opening/displaying it.
    """
    src = src.strip()
    if not src:
        return None

    candidate = Path(src)
    # Fast-path rejection for obviously absolute input. This is a cheap pre-check,
    # NOT the security boundary -- pathlib's is_absolute() has platform quirks
    # (e.g. "/etc/passwd" is not considered absolute on Windows), so it must never
    # be relied on alone; the relative_to() check below is authoritative regardless.
    if candidate.is_absolute():
        return None

    if candidate.suffix.lower() not in _ALLOWED_IMAGE_EXTENSIONS:
        return None

    # Markdown generated by backend.py already writes refs as "images/<filename>".
    # Drop a leading "images" component if present so both that form and a bare
    # "<filename>" resolve the same way, always anchored under base_dir below --
    # never onto the process's current working directory.
    parts = candidate.parts
    if parts and parts[0].lower() == _IMAGES_DIR.name.lower():
        candidate = Path(*parts[1:]) if len(parts) > 1 else Path()

    # Resolved fresh on every call (not cached) so the containment check always
    # reflects the current filesystem state.
    base_dir = _IMAGES_DIR.resolve()
    try:
        resolved = (base_dir / candidate).resolve()
    except (OSError, RuntimeError):
        return None

    # The real containment check: resolve() follows symlinks and normalizes ".."
    # segments, so `resolved` is the actual real path the OS would open. relative_to()
    # raises ValueError if that real path is not base_dir itself or a descendant of
    # it -- an ancestry check on the resolved path, not a string-prefix comparison.
    try:
        resolved.relative_to(base_dir)
    except ValueError:
        return None

    return resolved


def render_markdown_with_local_images(md: str):
    matches = list(_MD_IMG_RE.finditer(md))
    if not matches:
        st.markdown(md, unsafe_allow_html=False)
        return

    parts: List[Tuple[str, str]] = []
    last = 0
    for m in matches:
        before = md[last : m.start()]
        if before:
            parts.append(("md", before))

        alt = (m.group("alt") or "").strip()
        src = (m.group("src") or "").strip()
        parts.append(("img", f"{alt}|||{src}"))
        last = m.end()

    tail = md[last:]
    if tail:
        parts.append(("md", tail))

    i = 0
    while i < len(parts):
        kind, payload = parts[i]

        if kind == "md":
            st.markdown(payload, unsafe_allow_html=False)
            i += 1
            continue

        alt, src = payload.split("|||", 1)

        caption = None
        if i + 1 < len(parts) and parts[i + 1][0] == "md":
            nxt = parts[i + 1][1].lstrip()
            if nxt.strip():
                first_line = nxt.splitlines()[0].strip()
                mcap = _CAPTION_LINE_RE.match(first_line)
                if mcap:
                    caption = mcap.group("cap").strip()
                    rest = "\n".join(nxt.splitlines()[1:])
                    parts[i + 1] = ("md", rest)

        if src.startswith("http://") or src.startswith("https://"):
            st.image(src, caption=caption or (alt or None), use_container_width=True)
        else:
            img_path = _resolve_image_path(src)
            if img_path is not None and img_path.exists():
                st.image(str(img_path), caption=caption or (alt or None), use_container_width=True)
            else:
                st.warning(f"Image not found: `{src}` (looked for `{img_path}`)")

        i += 1


# -----------------------------
# ✅ NEW: Past blogs helpers
# -----------------------------
def list_past_blogs() -> List[Path]:
    """
    Returns .md files in current working directory, newest first.
    Filters out obvious non-blog markdown files if needed.
    """
    cwd = Path(".")
    files = [p for p in cwd.glob("*.md") if p.is_file()]
    files.sort(key=lambda p: p.stat().st_mtime, reverse=True)
    return files


def read_md_file(p: Path) -> str:
    return p.read_text(encoding="utf-8", errors="replace")


def extract_title_from_md(md: str, fallback: str) -> str:
    """
    Use first '# ' heading as title if present.
    """
    for line in md.splitlines():
        if line.startswith("# "):
            t = line[2:].strip()
            return t or fallback
    return fallback


# -----------------------------
# Streamlit UI
# -----------------------------
st.set_page_config(page_title="AI Investment Due Diligence Intelligence Agent", layout="wide")


def _require_app_access() -> None:
    """Password gate for the whole app (report generation + KB upload + past-report
    browsing) -- runs first, before any other content, and st.stop()s the script if
    not authenticated. This is the fix for the trust-boundary gap noted earlier: the
    KB-upload button calls the ingestion service in-process, bypassing the ingestion
    API's own INGESTION_API_KEY check entirely, so without this gate anyone who can
    load this page could ingest documents. A no-op (APP_ACCESS_KEY unset) only for
    local/dev use -- the visible warning below makes that state impossible to miss
    rather than silently open, mirroring the same pattern used for INGESTION_API_KEY
    in ingestion/api.py."""
    if not settings.APP_ACCESS_KEY:
        st.warning(
            "APP_ACCESS_KEY is not set — this app is running with no access gate. "
            "Set it before exposing this app beyond your own machine.",
            icon="⚠️",
        )
        return

    if st.session_state.get("app_authenticated"):
        return

    st.title("🔒 Access Required")
    entered = st.text_input("Access key", type="password", key="app_access_key_input")
    if st.button("Unlock"):
        if hmac.compare_digest(entered, settings.APP_ACCESS_KEY):
            st.session_state["app_authenticated"] = True
            st.rerun()
        else:
            st.error("Incorrect access key.")
    st.stop()


_require_app_access()

# Initialize the SQLite/vector backends once, before any sidebar content reads them
# (the Memory section calls launch_runner.list_recent_launches() early on).
_init_ingestion_backend()

st.title("AI Investment Due Diligence Intelligence Agent")
st.caption("Past reports are in the left sidebar. Use the chat bar at the bottom to generate a new due diligence report.")

if "session_id" not in st.session_state:
    st.session_state["session_id"] = str(uuid.uuid4())
session_id = st.session_state["session_id"]

as_of = st.date_input("As-of date", value=date.today())

with st.sidebar:
    st.header("🧠 Memory")
    user_id = st.text_input(
        "Your ID (name or email, optional)",
        value=st.session_state.get("user_id", ""),
        help="Enter the same ID across visits to enable long-term memory and recall of past due diligence reports. Leave blank to stay session-only.",
    )
    st.session_state["user_id"] = user_id
    st.caption(f"Session: `{session_id[:8]}…`")

    recent_launches = launch_runner.list_recent_launches(user_id, session_id, limit=10)
    if not recent_launches:
        st.caption("No reports recorded yet.")
    else:
        st.caption("Recent reports")
        for launch in recent_launches:
            label = f"{launch.blog_title or launch.topic} · {launch.created_at.date().isoformat()}"
            if st.button(f"🧠 {label}", key=f"mem_launch_{launch.id}"):
                st.session_state["last_out"] = {
                    "plan": None,
                    "evidence": [],
                    "image_specs": [],
                    "final": launch.final_markdown,
                }
                st.session_state["topic_prefill"] = launch.blog_title or launch.topic

    st.divider()
    st.header("📄 Knowledge Base")
    st.caption(
        "Upload a document to make it searchable by the agent (requires Weaviate "
        "running via `docker compose up -d`). Note: this calls the ingestion "
        "pipeline in-process, not through the API-key-gated FastAPI endpoint -- "
        "anyone who can reach this Streamlit app can ingest documents."
    )

    uploaded_file = st.file_uploader(
        "Upload PDF / DOCX / TXT / Markdown",
        type=["pdf", "docx", "txt", "md", "markdown"],
        key="kb_uploader",
    )
    if uploaded_file is not None and st.button("⬆️ Ingest into Knowledge Base"):
        service = build_service()
        try:
            document = service.ingest_upload(_StreamlitUploadAdapter(uploaded_file))
        except DuplicateDocumentError as exc:
            st.warning(f"Already ingested (document `{exc.existing_document_id}`).")
        except (UnsupportedFileTypeError, InvalidFilenameError, InvalidCollectionNameError, FileTooLargeError) as exc:
            st.error(str(exc))
        except Exception:
            st.error("Upload failed due to an internal error. Check the app logs.")
        else:
            # Synchronous, not backgrounded like the FastAPI path -- Streamlit has no
            # background-task primitive, so the spinner is what keeps this from
            # looking frozen. The extraction/chunk-count guards in loaders.py and
            # service.py bound how long this can actually take.
            with st.spinner(f"Chunking, embedding, and indexing `{document.original_filename}`…"):
                service.process_document(document.id)
            processed = service.get_document(document.id)
            if processed.status == IngestionStatus.COMPLETED.value:
                st.success(f"Indexed `{processed.original_filename}` — {processed.chunk_count} chunk(s). It's now searchable.")
            else:
                st.error(f"Indexing failed: {processed.error_message or 'unknown error'}. Is Weaviate running (`docker compose up -d`)?")

    st.divider()
    st.header("Past Reports")

    past_files = list_past_blogs()
    if not past_files:
        st.caption("No saved reports found (*.md in current folder).")
        selected_md_file = None
    else:
        # Build labels from file name + (optional) parsed title
        options: List[str] = []
        file_by_label: Dict[str, Path] = {}
        for p in past_files[:50]:
            try:
                md_text = read_md_file(p)
                title = extract_title_from_md(md_text, p.stem)
            except Exception:
                title = p.stem
            label = f"{title}  ·  {p.name}"
            options.append(label)
            file_by_label[label] = p

        selected_label = st.radio(
            "Select a report to load",
            options=options,
            index=0,
            label_visibility="collapsed",
        )
        selected_md_file = file_by_label.get(selected_label)

        if st.button("📂 Load selected report"):
            if selected_md_file:
                md_text = read_md_file(selected_md_file)
                # Load into session_state as if it were a run output
                st.session_state["last_out"] = {
                    "plan": None,          # old files don't include plan
                    "evidence": [],        # old files don't include evidence
                    "image_specs": [],     # optional (not persisted)
                    "final": md_text,      # markdown body
                }
                # also update the topic input to the title (best-effort) without changing UI
                st.session_state["topic_prefill"] = extract_title_from_md(md_text, selected_md_file.stem)

    

# Bottom chat-style input: Enter/Send triggers generation.
incoming_topic = st.chat_input("Type the company/topic to research and press Enter to generate")
run_btn = bool(incoming_topic and incoming_topic.strip())
topic = (incoming_topic or "").strip()

# Storage for latest run
if "last_out" not in st.session_state:
    st.session_state["last_out"] = None

# Layout
tab_plan, tab_evidence, tab_preview, tab_images, tab_logs = st.tabs(
    ["🧭 Strategy Plan", "🔎 Market Evidence", "📝 Report Preview", "🖼️ Visuals", "🧾 Logs"]
)

logs: List[str] = []


def log(msg: str):
    logs.append(msg)


if run_btn:
    if not topic:
        st.warning("Please enter a company/topic to research.")
        st.stop()

    inputs: Dict[str, Any] = launch_runner.prepare_inputs(topic, as_of, user_id, session_id)

    status = st.status("Running graph…", expanded=True)
    progress_area = st.empty()
    token_area = st.empty()

    current_state: Dict[str, Any] = {}
    last_node = None
    token_buffer = ""
    last_token_node: Optional[str] = None

    def _render_summary(state: Dict[str, Any]) -> None:
        summary = {
            "mode": state.get("mode"),
            "needs_research": state.get("needs_research"),
            "queries": state.get("queries", [])[:5] if isinstance(state.get("queries"), list) else [],
            "evidence_count": len(state.get("evidence", []) or []),
            "tasks": len((state.get("plan") or {}).get("tasks", [])) if isinstance(state.get("plan"), dict) else None,
            "images": len(state.get("image_specs", []) or []),
            "sections_done": len(state.get("sections", []) or []),
        }
        progress_area.json(summary)

    def _tool_line(kind: str, data: Dict[str, Any]) -> str:
        tool_name = data.get("tool", "tool")
        bits = []
        if "index" in data and "total" in data:
            bits.append(f"{data['index']}/{data['total']}")
        if data.get("query"):
            bits.append(str(data["query"])[:120])
        if data.get("filename"):
            bits.append(str(data["filename"]))
        if kind == "tool_end":
            if "result_count" in data:
                bits.append(f"{data['result_count']} result(s)")
            elif "evidence_count" in data:
                bits.append(f"{data['evidence_count']} item(s)")
        icon = "🔧" if kind == "tool_start" else "✅"
        detail = " · ".join(bits)
        return f"{icon} {tool_name}" + (f" ({detail})" if detail else "")

    run_config = {
        "callbacks": [get_observability_handler()],
        "metadata": {"session_id": session_id, "user_id": user_id or None},
    }
    for event in run_graph_streaming(app, inputs, config=run_config):
        kind = event.get("kind")

        if kind == "node_end":
            node_name = event.get("node")
            if node_name and node_name != last_node:
                status.write(f"➡️ Node: `{node_name}`")
                last_node = node_name
            log(f"[node_end] {node_name}")

        elif kind == "token":
            node_name = event.get("node")
            text = event.get("text") or ""
            if node_name != last_token_node:
                token_buffer += f"\n\n--- {node_name or 'model'} ---\n"
                last_token_node = node_name
            token_buffer += text
            token_area.text(token_buffer[-4000:])

        elif kind in ("tool_start", "tool_end"):
            data = event.get("data") or {}
            line = _tool_line(kind, data)
            status.write(line)
            log(f"[{kind}] {json.dumps(data, default=str)[:500]}")

        elif kind == "status":
            state = event.get("state")
            if isinstance(state, dict):
                current_state = state
                _render_summary(current_state)
            elif event.get("text"):
                status.write(f"ℹ️ {event['text']}")
                log(f"[status] {event['text']}")

        elif kind == "final":
            out = event.get("state") or current_state
            st.session_state["last_out"] = out
            status.update(label="✅ Done", state="complete", expanded=False)
            log("[final] received final state")
            launch_runner.record_result(user_id, session_id, inputs, out)

        elif kind == "error":
            message = event.get("text") or "Generation failed."
            st.error(message)
            status.update(label="⚠️ Streaming degraded", state="error", expanded=True)
            log(f"[error] {message}")

# Render last result (if any)
out = st.session_state.get("last_out")
if out:
    # --- Plan tab ---
    with tab_plan:
        st.subheader("Strategy Plan")
        plan_obj = out.get("plan")
        if not plan_obj:
            st.info("No plan found in output.")
        else:
            if hasattr(plan_obj, "model_dump"):
                plan_dict = plan_obj.model_dump()
            elif isinstance(plan_obj, dict):
                plan_dict = plan_obj
            else:
                plan_dict = json.loads(json.dumps(plan_obj, default=str))

            st.write("**Report Title:**", plan_dict.get("blog_title"))
            cols = st.columns(3)
            cols[0].write("**Audience:** " + str(plan_dict.get("audience")))
            cols[1].write("**Tone:** " + str(plan_dict.get("tone")))
            cols[2].write("**Report type:** " + str(plan_dict.get("blog_kind", "")))

            tasks = plan_dict.get("tasks", [])
            if tasks:
                df = pd.DataFrame(
                    [
                        {
                            "id": t.get("id"),
                            "title": t.get("title"),
                            "target_words": t.get("target_words"),
                            "requires_research": t.get("requires_research"),
                            "requires_citations": t.get("requires_citations"),
                            "requires_code": t.get("requires_code"),
                            "tags": ", ".join(t.get("tags") or []),
                        }
                        for t in tasks
                    ]
                ).sort_values("id")
                st.dataframe(df, use_container_width=True, hide_index=True)

                with st.expander("Task details"):
                    st.json(tasks)

    # --- Evidence tab ---
    with tab_evidence:
        st.subheader("Market Evidence")
        evidence = out.get("evidence") or []
        if not evidence:
            st.info("No evidence returned (possible closed_book mode or no Tavily key/results).")
        else:
            rows = []
            for e in evidence:
                if hasattr(e, "model_dump"):
                    e = e.model_dump()
                rows.append(
                    {
                        "title": e.get("title"),
                        "published_at": e.get("published_at"),
                        "source": e.get("source"),
                        "url": e.get("url"),
                    }
                )
            st.dataframe(pd.DataFrame(rows), use_container_width=True, hide_index=True)

    # --- Preview tab ---
    with tab_preview:
        st.subheader("Due Diligence Report Preview")
        final_md = out.get("final") or ""
        if not final_md:
            st.warning("No final markdown found.")
        else:
            render_markdown_with_local_images(final_md)

            plan_obj = out.get("plan")
            if hasattr(plan_obj, "blog_title"):
                blog_title = plan_obj.blog_title
            elif isinstance(plan_obj, dict):
                blog_title = plan_obj.get("blog_title", "due_diligence_report")
            else:
                # fallback: parse from markdown title
                blog_title = extract_title_from_md(final_md, "due_diligence_report")

            md_filename = f"{safe_slug(blog_title)}.md"
            st.download_button(
                "⬇️ Download Markdown",
                data=final_md.encode("utf-8"),
                file_name=md_filename,
                mime="text/markdown",
            )

            bundle = bundle_zip(final_md, md_filename, Path("images"))
            st.download_button(
                "📦 Download Bundle (MD + images)",
                data=bundle,
                file_name=f"{safe_slug(blog_title)}_bundle.zip",
                mime="application/zip",
            )

    # --- Images tab ---
    with tab_images:
        st.subheader("Visuals")
        specs = out.get("image_specs") or []
        images_dir = Path("images")

        if not specs and not images_dir.exists():
            st.info("No visuals generated for this report.")
        else:
            if specs:
                st.write("**Image plan:**")
                st.json(specs)

            if images_dir.exists():
                files = [p for p in images_dir.iterdir() if p.is_file()]
                if not files:
                    st.warning("images/ exists but is empty.")
                else:
                    for p in sorted(files):
                        st.image(str(p), caption=p.name, use_container_width=True)

                z = images_zip(images_dir)
                if z:
                    st.download_button(
                        "⬇️ Download Images (zip)",
                        data=z,
                        file_name="images.zip",
                        mime="application/zip",
                    )

    # --- Logs tab ---
    with tab_logs:
        st.subheader("Logs")
        if "logs" not in st.session_state:
            st.session_state["logs"] = []
        if logs:
            st.session_state["logs"].extend(logs)

        st.text_area("Event log", value="\n\n".join(st.session_state["logs"][-80:]), height=520)
else:
    st.info("Enter a company/topic to research and press Enter to generate the report.")
